name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Ionic CLI
        working-directory: ./frontend
        run: npm install -g @ionic/cli

      - name: Build frontend
        working-directory: ./frontend
        run: ionic build

      - name: Run tests
        working-directory: ./frontend
        run: npm run test -- --no-watch --browsers ChromeHeadless

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: ./frontend/www

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests
        working-directory: ./backend
        run: npm test 

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Download artifacts
      - uses: actions/download-artifact
        with: 
          name: www
          path: ./frontend/www

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/www
          publish_branch: gh-pages
          publish_repo: ${{ github.repository }}
          destination_dir: frontend
          force_orphan: true
          commit_message: "Deploy frontend to GitHub Pages"
          user_name: "GitHub Actions"
          